name: TTT-CLI-Local
description: 'Execute a scenario using the CLI'
branding:
  icon:  upload-cloud
  color: orange
author: BMC
inputs:
 hciconnection:
        # Host/IP adress input from users
        description: HCI Connection
        default: "CW13.bmc.com"
        required: true
      port:
        # passticket input from the user.
        description: Port
        default: "16196"
        required: true
      testFolderPath:
        # passticket input from the user.
        description: Test Location Path
        default: "C:\\Users\\aasati\\Compuware\\Workbench\\workspace\\CLI_CWKTCOBX\\Tests\\Scenarios"
        required: true
      workspace:
        # Workspcae location of the customer input from the user.
        description: Customized Workspace
        default: "C:\\Users\\aasati\\git\\TTT\\work\\workspace\\Security_Vulnerability\\TopazCliWkspc"
        required: true        
      repository_server:
        # repository server input from the user.
        description: Repository Server
        default: "http://vw-dtw-xat-01.adprod.bmc.com:48231/totaltestapi/"
        required: true
      userId:
        # repository server input from the user.
        description: HCI User ID
        default: ""
        required: true
      password:
        # repository server input from the user.
        description: HCI password
        default: ""
        required: true
outputs:
  description: 'The output shuld be stored in testLocationPath which user need to provide'
